CI: azure
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7'
cxx_compiler: vs2017
extend_keys:
- ignore_version
- extend_keys
- ignore_build_only_deps
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  curl:
    max_pin: x
python: '3.6'
r_base: '3.4'
target_platform: win-64
vc: '14'
